TheCacophonyProject/classifier-pipeline

- ml_tools/model.py
- ml_tools/tools.py
To avoid output mixing with JSON output.
> Replace classifier related prints with logging

- classifier_TEMPLATE.yaml
- classify.py
- classify/classifyconfig.py
- classify/clipclassifier.py
- classify/previewer.py
- extract.py
- ml_tools/cptvfileprocessor.py
- ml_tools/trackdatabase.py
- track/cptvtrackextractor.py
- track/track.py
- track/trackextractor.py
Changes -
- Tracks positions are output from the classifier. 
-  New preview mode 'raw' that does't output tracking rectangles.  (For new track based tagging ID)
> Output tracks

- track/cptvtrackextractor.py
- track/track.py
- track/trackextractor.py
Get extract running, and stop it rejecting all videos due to the duration no longer being set.
> Fix extract

- classifier_TEMPLATE.yaml
- requirements.txt
- track/cptvtrackextractor.py
- track/trackextractor.py
- track/trackingconfig.py
The extra tracks were caused by the mask changing and thus the mass of the track.   The mass is now calculated from the original mask before dilating so it should work ok now. 
I have also fixed the security warning in pyyaml.
> Fix extra tracks

- INSTRUCTIONS.md
Pretty shallow, but reduces the WTF moments by one.
> Document making classifier.yaml

- build.py
- ml_tools/cptvfileprocessor.py
Typos, readability, and better error output.
> Minor tweaks

- classify.py
- classify/classifyconfig.py
- extract.py
- ml_tools/config.py
- requirements.txt
- track/cptvtrackextractor.py
- track/extractconfig.py
- track/trackingconfig.py
Using attrs based config classses instead of namedtuple means that config can be handled more directly.
> Simplify config handling

- classify.py
- classify/clipclassifier.py
- ml_tools/previewer.py
- track/trackingconfig.py
text.    This will give a better experience for the user to understand tracking when they are labelling by tracks. 
(Also fix bug that stops processor from running due to path changes)
> Update previewer to add mode where the boxes are output but not the

- classify.py
- classify/main.py
This is required to allow it be run from inside a PEX bundle.
> Allow classify's main function to be imported

- .travis.yml
- build.py
- check-style
- classify/clipclassifier.py
- classify/main.py
- classify/trackprediction.py
- evaluate.py
- extract.py
- ml_tools/cptvfileprocessor.py
- ml_tools/dataset.py
- ml_tools/model.py
- ml_tools/mpeg_creator.py
- ml_tools/previewer.py
- ml_tools/test_rectangle.py
- ml_tools/tools.py
- ml_tools/trackdatabase.py
- ml_tools/visualise.py
- model_crnn.py
- track/cptvtrackextractor.py
- track/framebuffer.py
- track/region.py
- track/track.py
- track/trackextractor.py
- track/trackingconfig.py
- train.py
.. and have TravisCI ensure that formatted remains consistent.
> Apply Black code formatter to all source files

- classifier_TEMPLATE.yaml
- ml_tools/config.py
- ml_tools/model.py
- train.py
- train/config.py
- train/search.py
- train/train.py
- removed unused dataset arg
- moved training config to classifier.yaml
- split out search and train code into their own files
> Clean up train.py

- classifier_TEMPLATE.yaml
- ml_tools/model.py
- model_crnn.py
- track/trackextractor.py
- train/train.py
fixes #65 
also fixed bug with learning_rate from config loading as a string
change model checkpoint directory to load from config
> fixed shape mismatch bug, caused by wrong start, end time

- classify/clipclassifier.py
- model_crnn.py
added train_config to model initialise
> fixed classifier not running

- classify/classifyconfig.py
- classify/clipclassifier.py
- classify/main.py
- ml_tools/buffercache.py
- ml_tools/dataset.py
- ml_tools/framecache.py
- ml_tools/previewer.py
- ml_tools/trackdatabase.py
- track/framebuffer.py
- track/track.py
- track/trackextractor.py
Added a config option classify.cache_to_disk which will write frames to a temp h5py file.
Also changed TrackExtractor Mask to be int32 instead of float32
> Memory fix

- README.md
- classifier_TEMPLATE.yaml
and added missing cache_to_disk in template
> Add install instructions

- classifier_TEMPLATE.yaml
- load/clip.py
- load/cliploader.py
- load/loadconfig.py
- ml_tools/tools.py
- ml_tools/trackdatabase.py
- track/track.py
> Use human tags

- track/trackextractor.py
This was causing processing to crash for recordings with many tracks.
Fixes #82
> Fixed a reference to incorrect attribute

- .travis.yml
- config/test_timewindow.py
- config/thermalconfig.py
- config/timewindow.py
- piclassifier/cptvrecorder.py
- piclassifier/motiondetector.py
Moved time window, sunrise and sunset calculation into it's own class.
Simplified the use. 
Fixed problem with checking if we are within the time window
> Fix time window

- piclassifier/motiondetector.py
also keep last frame in thermal window when not recording to keep management d camera preview working
> Fix reference

- .travis.yml
- classifier_TEMPLATE.yaml
- config/config.py
- config/test_timewindow.py
- config/thermalconfig.py
- config/timewindow.py
- ml_tools/logs.py
- motiontest.py
- piclassifier/cameras/boson.py
- piclassifier/cameras/lepton3.py
- piclassifier/cameras/rawframe.py
- piclassifier/cptvrecorder.py
- piclassifier/headerinfo.py
- piclassifier/motiondetector.py
- piclassifier/piclassifier.py
- piclassifier/piclassify.py
- piclassifier/telemetry.py
- service.py
Generalize frame
Add ability to specify camera type
tested on pi with latest leptond
> Stream socket

- classifier_TEMPLATE.yaml
- classify/clipclassifier.py
- classify/main.py
- ml_tools/trackdatabase.py
Add model_file parameter to classify
also add the background frame to load
> added model param to classify

- classify/clipclassifier.py
- classify/main.py
- classify/trackprediction.py
- ml_tools/kerasmodel.py
- ml_tools/model.py
- ml_tools/newmodel.py
Added basic new model class and modified classify.py to use old or new model depending on file provided
> integrate new model format

- classifier_TEMPLATE.yaml
- ml_tools/model.py
- model_crnn.py
- model_resnet.py
set optical flow to false by default, added extra labels, defualt false for cache_to_disk
Fixed kernel size not being loaded correctly.
> updated default tempate

- classify/clipclassifier.py
- classify/trackprediction.py
add all frame predictions to metadata output, so we can save this in the database
moved smooth prediction into trackprediction class, and keeping a copy of un smoothed prediction data
> Add prediction output

- ml_tools/imageprocessing.py
- ml_tools/preprocess.py
Cache to disk, loaded frames as float16 which cv2.resize doesn't like
> Fix dtype bug

- .travis.yml
- ml_tools/imageprocessing.py
- ml_tools/kerasmodel.py
- ml_tools/preprocess.py
- smoketest/test-config.yaml
This is needed for the latest model whcih does not use the dot movement channel
> added no dots options

- ml_tools/kerasmodel.py
- ml_tools/preprocess.py
New model requires thermal median subtraction and clipping for thermal frames, in the preprocess stage
> Add new model preprocessing

- classify/clipclassifier.py
- load/clip.py
- ml_tools/preprocess.py
Check that some components were found in background calculation
If some frames cant be classified, skip them and continue trying rather than returning
Also check that some valid frames exist in preprocess before continuing
> fix minior issues with latest version

- load/clip.py
- requirements.txt
Use background frame if is available in cptv file
> Use background

- load/clip.py
- load/cliptrackextractor.py
- ml_tools/imageprocessing.py
- ml_tools/preprocess.py
- track/track.py
Filtered frame values should be normalized to be within 0 -> 255, especially for lepton3.5 sensors
Blank frames should be cropped to the clip resolution
> normalize filtered frame and crop blank frames

- load/clip.py
- ml_tools/imageprocessing.py
- ml_tools/kerasmodel.py
- ml_tools/preprocess.py
- track/framebuffer.py
Numpy wont work out the max / min of an array with width  / height of 0
Also handle edge case where all frames are FFC
Also return zeros as Flow so no errors are thrown if we dont calculate opt_flow
> Fix numpy exception

- classify/clipclassifier.py
- classify/main.py
- classify/trackprediction.py
- config/classifyconfig.py
- config/defaultconfig.py
- evaluate/evaluateresults.py
- evaluate/main.py
- kalman/kalmanpredictor.py
- load/clip.py
- load/cliploader.py
- load/cliptrackextractor.py
- load/load.py
- ml_tools/cptvfileprocessor.py
- ml_tools/dataset.py
- ml_tools/datasetstructures.py
- ml_tools/kerasmodel.py
- ml_tools/model.py
- ml_tools/preprocess.py
- ml_tools/previewer.py
- ml_tools/tools.py
- ml_tools/trackdatabase.py
- ml_tools/visualise.py
- model_crnn.py
- piclassifier/piclassifier.py
- piclassifier/piclassify.py
- tests/testconfig.py
- track/cptvtrackextractor.py
- track/framebuffer.py
- track/region.py
- track/track.py
Added multiple model files to config, and all results to output metadata
> Run all models

- classify/clipclassifier.py
- classify/trackprediction.py
- load/clip.py
- load/cliptrackextractor.py
- ml_tools/frame.py
- ml_tools/preprocess.py
- requirements.txt
- track/track.py
Make sure to garbage collect after using a model
Dont use background frame in tracking 
Update the preprocessing to work with frame object instead of ndarray
> Fix processing

- config/thermalconfig.py
- config/timewindow.py
- motiontest.py
- piclassifier/monitorconfig.py
- piclassifier/piclassifier.py
- piclassifier/piclassify.py
- pirequirements.txt
- requirements.txt
Restart classifier on config change
> Monitor config

- README.md
- src/classify/thumbnail.py
> Fix thumbnail error

- pyproject.toml
- src/config/test_timewindow.py
- src/config/thermalconfig.py
- src/piclassifier/piclassifier.py
- tests/config.toml
ability to turn of tracking and just do motion detection
also less logs
> Toggle tracking

- docker/classifier-docker.yaml
- docker/latestmodel.py
- src/classify/clipclassifier.py
- src/classify/trackprediction.py
- src/ml_tools/forestmodel.py
- src/ml_tools/interpreter.py
- src/track/cliptracker.py
- src/track/track.py
Use random forest model to filter false positive tracks
Also expose tracking score
And cap confidences fo short tracks if not false positive
> New rf support

- docker/latestmodel.py
- src/classify/clipclassifier.py
- src/config/timewindow.py
- src/ml_tools/datasetstructures.py
- src/ml_tools/interpreter.py
- src/track/cliptrackextractor.py
Use numpy as much as possible in making segments
Don't calculate filtered frame when loading cptv as it's not needed, just calculate background and cache frames
> Speed up classify

- .github/workflows/release.yml
- src/config/thermalconfig.py
- src/piclassifier/cptvrecorder.py
- src/piclassifier/dummyrecorder.py
- src/piclassifier/recorder.py
- src/piclassifier/throttledrecorder.py
fix throttled recored not checking sd space before starting a recording
> Check sd space

- .github/workflows/release.yml
- pyproject.toml
- src/classify/clipclassifier.py
- src/classify/main.py
- src/config/config.py
- src/extract.py
- src/ml_tools/forestmodel.py
- src/ml_tools/interpreter.py
- src/ml_tools/preprocess.py
- src/ml_tools/rawdb.py
- src/ml_tools/thermalwriter.py
- src/piclassifier/cptvmotiondetector.py
- src/piclassifier/motiondetector.py
- src/piclassifier/piclassifier.py
- src/track/clip.py
- src/track/cliptracker.py
- src/track/cliptrackextractor.py
- src/track/irtrackextractor.py
- src/track/track.py
- src/track/trackextractor.py
> Merged master

- src/classify/clipclassifier.py
- src/classify/trackprediction.py
- src/ml_tools/forestmodel.py
- src/piclassifier/piclassifier.py
PI classifications weren't being normalized
Forestmodel would fail from classify.py
> Fix issues
